### ISSUE TITLE
Create a debatecore footer

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#23]
Create a new footer (preferably as a component) redirecting to [debateco.re](https://debateco.re) and insert it in every subpage.

**Comment by jakubmanczak** [comment]
Not sure if *every* subpage is ideal. 🤔

Any user that needs to be reminded of the project's umbrella branding is already on the site, and most likely clicked through the main menu. A landing page change I mentioned in #28 could cover this.

**Comment by jakubmanczak** [comment]
> ZSK

Yeah sure, we're obviously not putting something like that on the website.

> Not sure if *every* subpage is ideal.

> The point of a footer is to exist on *every* subpage.

Point is, nobody is going to click on a link to the repository in the middle of a debate. Why bother cluttering it up, even negligibly, then? It doesn't exactly detract from the footer for it to be omitted where it makes sense. Not in my book, anyway.

Ultimately it probably depends on how it fits in with the rest of the UI on that page. We'll burn that bridge once we get to it.

**Comment by Mateusz-Dobrzynski** [comment]
>Nobody is going to click on a link to the repository in the middle of a debate.

That convinced me. But if that's the case, we need to figure out a consistent and understandable way of determining where the footer should be. Putting it arbitrarily on some pages and not doing it elsewhere would confuse the user.

**Comment by jakubmanczak** [comment]
<img width="1024" alt="image" src="https://github.com/debatecore/debate-tools/assets/56172798/05b101c5-f193-47ef-96e6-e5f260a9ca08">

Quick concept along with the present disclaimer.

**Comment by Mateusz-Dobrzynski** [comment]
I like it. It's minimalistic and clean. I like the idea of a horizontal gradient bar, but maybe that's a story for [debateco.re](https://debateco.re) page itself.

What's the difference between "[About](https://debateco.re/about)" (I guess that would be the link) and "Mission"? I'd rather have a footer with links to existing pages and then expand it.

**Comment by jakubmanczak** [comment]
None yet. I imagined it would be the difference between a local about page on the debate-tools site and an about page on the debatecore site, or something.

**Comment by jakubmanczak** [comment]
<img width="1240" alt="image" src="https://github.com/debatecore/debate-tools/assets/56172798/6851e081-efce-44f0-84b2-d7b4b9d0cd55">

Current look. I wonder if the text at the bottom should be included, it feels kind of barren without it.

**Comment by Mateusz-Dobrzynski** [comment]
Yeah, better keep that text.
