### ISSUE TITLE
Translate the "minutes" string in debate configuration

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#36]
In debate configuration the "minutes" string is hard-coded and isn't translated to other languages.

![IMG_20240423_125052.jpg](https://github.com/debatecore/debate-tools/assets/60257096/00f9c7bc-0d7e-48bb-81ea-4de2370349bf)

**Proposed changes**
- The string is translated to a current language
- The translation changes from singular to plural to match the number (_1 minute_, _5 minutes_, etc.). It will not be 100% correct in Polish, (Polish cardinal numerals are sometimes in Nominative and sometimes in Genitive, e.g. _2 minuty, 5 minut_) but it will still be an improvement. Besides, most UI designers don't care and just leave it at that

**Comment by jakubmanczak** [comment]
The solution I favour is to change the presentation of the UI: instead of inserting a number into a sentence, making it say something along the lines of "Minutes counter" etc. But that doesn't fit in with this minute increment widget.

We'll have to think.

**Comment by Mateusz-Dobrzynski** [comment]
If the UI ends up being rebuilt (e.g. as a part of #38), this issue will no longer exist. Since we're planning on restructuring the config view anyway, we should include avoiding this issue in our plans.
