### ISSUE TITLE
Fix custom image base64 conversion

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#67]
**Steps to reproduce**
- Go to debate conf
- Open console 
- Select a custom branding image
- Select a large file
- Go to debate clock view
- Notice an error pop up in console and the _Loading..._ text be displayed indefinitely

**Comment by jakubmanczak** [comment]
Sometimes, not even a large file - I've had an experience where a ~200x350px file didn't work while a larger one 700x700px one did. Canvas size doesn't correlate 1:1 with filesize of course, but the trend here was loosely correct. There's more than filesize to this.
