### ISSUE TITLE
Expand PND branding by a sponsors footer

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#73]
**Acceptance Criteria**
- When the PND branding is selected, an additional footer is displayed in the clock view
- The footer contains:
  - Sponsors' logos provided by the PND organizers
  - A debatecore logo (with a link to debateco.re website similarly to #23)

**Comment by jakubmanczak** [comment]
This was done on the last-minute with 550d3e40e2d84365ef74a3844f8b51b82a9ebd90 on the PND branch. Since sponsors change, I believe this is now obsolete.
