### ISSUE TITLE
Enhance the "debate finished" view

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#90]
During PND, I noticed one marshal misuse the clock, i.e. press the "back" button after every speech, because the clock had not been reset after a previous debate. This got me thinking that the "debate finished" view could be more direct in messaging that the debate is indeed over.

**Ideas**
- Dim and/or blur the screen and add a message displayed in the center, similarly to how it was done in [d0b3590](https://github.com/debatecore/debate-tools/commit/d0b3590db5c83e57fb7feab4391c688bd93b1ea2). I think "Debate Finished 🎉" was a good one;
- Add a "reset" button, possibly represented with a [repeat icon](https://lucide.dev/icons/repeat), setting the debate state back to stage one.

**Comment by jakubmanczak** [comment]
Agree about the `🎉` – will surely bring it back.

**Comment by jakubmanczak** [comment]
Going back to the report at hand though, wouldn't that cause the clock to display wrongful information about the current debate? Like, wrong motion, wrong team names? How does one miss all that?
